services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    healthcheck:
      test: curl --fail http://localhost:9200/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
  web:
    image: mmaggiezhou/foodtrucks-web 
    command: python3 app.py
    depends_on:
      es:
        condition: service_healthy
    ports:
      - 5000:5000
    # for local testing
    # volumes: 
    #   - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
