apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
          command: ["/usr/local/bin/docker-entrypoint.sh"]
          args: ["bin/elasticsearch", "-Ediscovery.type=single-node"]
          ports:
            - containerPort: 9200
